image:
  file: base.Dockerfile

tasks:
  - name: Dependencies
    init: |
      yay -Syu --noconfirm rust rust-src docker
  - name: Build
    init: cargo build
  - name: Clippy
    init: cargo clippy
  - name: Release
    init: cargo build --release
  - name: Docker images
    init: |
      docker build -f base.Dockerfile -t aur-autoupdater-base .
      docker build -f tests.Dockerfile -t aur-autoupdater-tests .
vscode:
  extensions:
    - matklad.rust-analyzer
    - serayuzgur.crates
    - eamodio.gitlens
    - editorconfig.editorconfig
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
