[nitpick]
minimum_version = "0.26.0"

[nitpick.styles]
include = [
    "gh://andreoliwa/nitpick/styles/editorconfig.toml",
    "pre-commit/main.toml",
    "pre-commit/general.toml",
    "pre-commit/bash.toml",
]
